### ISSUE TITLE
Problemas com a requisição da API

### ISSUE THREAD

**Issue by mr-cerebro** [Paulo-Lopes-Estevao/Api_Identity#3]
###### Ainda não consigo usar a API

Eu estou usando a função da biblioteca jQuery que pega requisições via ajax, e desde ontem não consigo, mas o problema desta vez é que não retorna nada, nem erro.

```
function consultarBI() {
    $.ajax({
        url: "https://ka6xhw.deta.dev/bi/003630676LA030",
        type: "GET",
        sucess: function(response) {
            console.log(response)
        }
    })
}
```
Já pesquisei sobre o assunto, e, todas as respostas foi dessa forma que estou usando...

Achei muito legal a tua API e quero pôr em um projeto que visará facilitar a pesquisa de dados.

Desde já, agradeço!

**Comment by Paulo-Lopes-Estevao** [comment]
já foi liberado o acesso para requisição de ambientes estaticos.
